#!/usr/bin/env bash
# Generation, without a template engine. Two mechanisms and no third:
#   marker substitution  — templates/*.tmpl carry @@NAME@@, replaced with sed
#   fragment assembly    — a head plus one rendered fragment per item, concatenated
# GitHub Actions' own ${{ }} passes through untouched, which is exactly why the markers are @@.

# Returns 1 and writes nothing when there are no components. A `jobs:` key with nothing under it
# is a file GitHub rejects, so for a repository with nothing to build the right artefact is no
# workflow at all — the process gates live in the carried workflows and do not need this one.
acb_render_ci() {
  local id t
  [[ -n "$(acb_components)" ]] || return 1
  cat "$ACB_ROOT/templates/ci.yml.head"
  for id in $(acb_components); do
    sed -e "s|@@ID@@|$id|g" \
        -e "s|@@CHECK_NAME@@|$(acb_check_name "$id")|g" \
        -e "s|@@RUNNER@@|$(acb_runner "$id")|g" \
        "$ACB_ROOT/templates/ci.yml.component"
    # Steps are assembled rather than templated: sed cannot loop, and a per-target step list is
    # the one place this file genuinely needs one.
    for t in $(acb_targets "$id"); do
      printf '      - name: %s\n        run: ./verify.sh %s\n' "$t" "$t"
    done
  done
}

acb_render_verify() {
  local id="$1" t targets
  targets="$(acb_targets "$id" | tr '\n' ' ')"; targets="${targets% }"
  cat <<EOS
#!/usr/bin/env bash
# The single entry point CI and a developer both run — same script, same targets, so the two
# cannot drift. Generated by 'acb init'; this file is yours and is never regenerated.
set -euo pipefail
cd "\$(dirname "\$0")"

TARGETS="${targets}"

run() { echo "==> \$*"; "\$@"; }

not_implemented() {
  echo "✗ ./verify.sh \$1 is not implemented yet." >&2
  echo "  Fill in target_\$1 below. Until then this component's CI is red, which is correct:" >&2
  echo "  a check that passes without checking anything is worse than no check." >&2
  exit 2
}
EOS
  # One function per declared target, with a MULTI-LINE body. Not decoration: the conformance
  # check plants a `false` on the line after the opening brace, and against a one-liner that
  # lands after the closing brace where it proves nothing. The target_ prefix is not decoration
  # either — `test` is a shell builtin, and a bare `test()` would shadow it for the whole script.
  for t in $targets; do
    printf 'target_%s() {\n  not_implemented %s\n}\n' "$t" "$t"
  done
  cat <<'EOS'

all() { local t; for t in $TARGETS; do "target_$t"; done; }

case "${1:-all}" in
  all) all ;;
  *)
    if [[ " $TARGETS " == *" ${1} "* ]]; then
      "target_${1}"
    else
      # 64, not 2: the conformance check distinguishes "this target exists but does nothing yet"
      # from "this target does not exist", and one shared code would make that check vacuous.
      echo "unknown target '${1}'. Known: $TARGETS all" >&2
      exit 64
    fi
    ;;
esac
EOS
}

# The declaration a fresh repository starts from. Deliberately one component rather than an empty
# list: `[]` is valid, but a first-time reader staring at it has nothing to copy.
acb_scaffold_config() {
  cat > .acb.json <<'JSON'
{
  "template": { "repo": "igor-ka/acb", "commit": "" },
  "process": {
    "doc": "docs/sdlc.md",
    "watched": ["^\\.claude/skills/", "^\\.github/workflows/", "^scripts/"],
    "prShapeHatch": "[multi-child]",
    "sdlcSyncHatch": "[skip-sdlc-sync]",
    "dependabotEcosystems": []
  },
  "components": [
    { "id": "app", "checkName": "App checks", "runner": "ubuntu-latest",
      "targets": ["install", "lint", "format", "test", "build"] }
  ]
}
JSON
}

acb_render_dependabot() {
  local eco
  cat "$ACB_ROOT/templates/dependabot.yml.head"
  for eco in $(acb_process_arr dependabotEcosystems); do
    sed -e "s|@@ECOSYSTEM@@|$eco|g" "$ACB_ROOT/templates/dependabot.yml.ecosystem"
  done
}

acb_render_ruleset() {
  local checks id
  # The two process checks are always required; component checks come from checkName, never from
  # the directory name. This list and ci.yml's job names are generated from one source, which is
  # the only reason they can be trusted to agree.
  checks="$( { echo "SDLC docs"; echo "PR shape"
               for id in $(acb_components); do acb_check_name "$id"; done
             } | jq -R . | jq -sc 'map({context: .})' )"
  # awk, not sed: a checkName containing & or | would corrupt a sed replacement.
  awk -v c="$checks" '{ gsub(/@@REQUIRED_CHECKS@@/, c); print }' \
      "$ACB_ROOT/templates/ruleset.json.tmpl"
}

acb_render_claude_md() {
  local rows id
  # shellcheck disable=SC2016  # the backticks are markdown code spans in the output, not syntax
  rows="$(for id in $(acb_components); do
            printf '| `%s` | `cd %s && ./verify.sh` | _document the dev command here_ |\n' "$id" "$id"
          done)"
  [[ -n "$rows" ]] || rows="_No components. The process layer applies regardless._"
  local tmp; tmp="$(mktemp)"
  { printf '| Component | Verify | Dev |\n| --- | --- | --- |\n'; printf '%s\n' "$rows"; } > "$tmp"
  # sed's `r` (read file) then `d` (delete the marker line), NOT `s`. A multi-line replacement
  # cannot travel through `s` portably, and `awk -v` rejects a newline in the assignment outright
  # on BSD — which is where this first broke.
  sed -e "/@@COMPONENT_TABLE@@/r $tmp" -e "/@@COMPONENT_TABLE@@/d" \
      "$ACB_ROOT/templates/CLAUDE.md.tmpl"
  rm -f "$tmp"
}

acb_cmd_init() {
  local dir="${1:-}" repo="" id p
  [[ -n "$dir" ]] || { echo "usage: acb init <dir> [--repo owner/name]" >&2; return 2; }
  [[ "${2:-}" == "--repo" ]] && repo="${3:-}"

  mkdir -p "$dir" || return 1
  cd "$dir" || return 1
  [[ -d .git ]] || git init -q -b main || return 1

  # The declaration comes first: everything below is generated from it, so an invalid one must
  # stop the run before any file is written.
  [[ -f .acb.json ]] || acb_scaffold_config
  ACB_CONFIG=".acb.json" acb_config_validate || return 1

  local ecos; ecos="$(acb_process_arr dependabotEcosystems | tr '\n' ' ')"; ecos="${ecos%% }"

  # Carried files: copied, never rendered. MANIFEST is the single answer to "is this carried?".
  while read -r p; do
    # Auto-merge is opt-in. It needs a per-repository GitHub App a fresh repository does not
    # have, so carrying it unconditionally ships a workflow that fails at "mint a token" on
    # every dependency bump. Declaring an ecosystem is the opt-in.
    if [[ "$p" == *dependabot-auto-merge.yml ]] && [[ -z "${ecos// }" ]]; then
      continue
    fi
    mkdir -p "$(dirname "$p")" || return 1
    cp "$ACB_ROOT/carried/$p" "$p" || return 1
  done < "$ACB_ROOT/MANIFEST"

  mkdir -p .github/workflows docs scripts || return 1
  # No components means no ci.yml at all, rather than one GitHub rejects.
  if acb_render_ci > .github/workflows/ci.yml; then :; else rm -f .github/workflows/ci.yml; fi
  acb_render_dependabot > .github/dependabot.yml || return 1
  acb_render_ruleset    > .github/ruleset.json   || return 1
  acb_render_claude_md  > CLAUDE.md              || return 1
  cp "$ACB_ROOT/templates/sdlc-example.md.tmpl"  docs/sdlc-example.md || return 1
  cp "$ACB_ROOT/templates/apply-ruleset.sh.tmpl" scripts/apply-ruleset.sh || return 1
  chmod +x scripts/apply-ruleset.sh
  for id in $(acb_components); do
    mkdir -p "$id" || return 1
    acb_render_verify "$id" > "$id/verify.sh" || return 1
    chmod +x "$id/verify.sh"
  done

  # Recorded LAST, so a run that died halfway leaves a repository `acb status` reports as
  # uninitialised rather than as up to date.
  local commit tmp
  commit="$(git -C "$ACB_ROOT" rev-parse HEAD)"
  tmp="$(mktemp)"
  jq --arg c "$commit" '.template.commit = $c' .acb.json > "$tmp" && mv "$tmp" .acb.json

  if [[ -n "$repo" ]]; then
    gh repo view "$repo" >/dev/null 2>&1 || \
      gh repo create "$repo" --private --source=. --remote=origin >/dev/null || return 1
    if [[ -n "${ecos// }" ]]; then
      gh variable set ACB_DEPENDABOT_ECOSYSTEMS --repo "$repo" --body "$ecos" >/dev/null || true
      echo "==> auto-merge needs a GitHub App. See 'Auto-merge setup' in the generated CLAUDE.md."
    fi
  fi

  echo "✓ initialised $dir at template commit ${commit:0:8}"
  echo "  CI is red until you fill in each component's verify.sh. That is correct."
  [[ -n "$repo" ]] && echo "  then: git add -A && git commit && git push, and scripts/apply-ruleset.sh"
  return 0
}
